"""improved seasons_teams and added is_curr_season

Revision ID: 356adb4af90f
Revises: 5b4c87301365
Create Date: 2025-05-01 22:15:03.617991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356adb4af90f'
down_revision: Union[str, None] = '5b4c87301365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons',
                  sa.Column('is_current_season', sa.Boolean(), nullable=False, default=False))
    op.add_column('seasons_teams',
                  sa.Column('position', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('games', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('wins', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('draws', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('loses', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('scored_goals', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('conceded_goals', sa.Integer(), nullable=False, default=0))
    op.add_column('seasons_teams',
                  sa.Column('points', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons_teams', 'points')
    op.drop_column('seasons_teams', 'conceded_goals')
    op.drop_column('seasons_teams', 'scored_goals')
    op.drop_column('seasons_teams', 'loses')
    op.drop_column('seasons_teams', 'draws')
    op.drop_column('seasons_teams', 'wins')
    op.drop_column('seasons_teams', 'games')
    op.drop_column('seasons_teams', 'position')
    op.drop_column('seasons', 'is_current_season')
    # ### end Alembic commands ###
